// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Apt
{
    public int Id { get; set; }

    public int OwnerId { get; set; }

    public string AptCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double? Area { get; set; }

    public string Address { get; set; }

    public string AddressLink { get; set; }

    public int ProvinceId { get; set; }

    public int DistrictId { get; set; }

    public int WardId { get; set; }

    public long RentPrice { get; set; }

    public long? PilePrice { get; set; }

    public int CategoryId { get; set; }

    public int StatusId { get; set; }

    public int NumberOfRoom { get; set; }

    public int AvailableRoom { get; set; }

    public int ApproveStatusId { get; set; }

    public string Note { get; set; }

    public double? Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<AptImage> AptImages { get; set; } = new List<AptImage>();

    public virtual ICollection<AptUtility> AptUtilities { get; set; } = new List<AptUtility>();

    public virtual AptCategory Category { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<CurrentResident> CurrentResidents { get; set; } = new List<CurrentResident>();

    public virtual ICollection<MaintenanceRequest> MaintenanceRequests { get; set; } = new List<MaintenanceRequest>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual AptStatus StatusNavigation { get; set; }
}