// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class CurrentResident
{
    public int Id { get; set; }

    public int AptId { get; set; }

    public int AccountId { get; set; }

    public DateTime MoveInDate { get; set; }

    public DateTime? MoveOutDate { get; set; }

    public int StatusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual Apt Apt { get; set; }
}