// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class MaintenanceRequest
{
    public int Id { get; set; }

    public int AptId { get; set; }

    public int LesseeId { get; set; }

    public string Description { get; set; }

    public int Priority { get; set; }

    public int AgentId { get; set; }

    public int ApproveStatusId { get; set; }

    public int ProgressStatusId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? Status { get; set; }

    public virtual Account Agent { get; set; }

    public virtual Apt Apt { get; set; }

    public virtual Account Lessee { get; set; }
}