// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Order
{
    public string Id { get; set; }

    public int ContractId { get; set; }

    public int LessorId { get; set; }

    public int LesseeId { get; set; }

    public decimal Amount { get; set; }

    public int TransactionTypeId { get; set; }

    public int TransactionStatusId { get; set; }

    public DateTime DueDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Account Lessee { get; set; }

    public virtual Account Lessor { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual WalletTransaction WalletTransaction { get; set; }
}