// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class WalletTransaction
{
    public int Id { get; set; }

    public string OrderId { get; set; }

    public int WalletId { get; set; }

    public decimal Amount { get; set; }

    public int TransactionTypeId { get; set; }

    public int TransactionStatusId { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual Wallet Wallet { get; set; }
}