// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Account
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PhoneNumber { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string AvatarUrl { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<AccountToken> AccountTokens { get; set; } = new List<AccountToken>();

    public virtual ICollection<AccountVerification> AccountVerifications { get; set; } = new List<AccountVerification>();

    public virtual ICollection<Contract> ContractAgents { get; set; } = new List<Contract>();

    public virtual ICollection<Contract> ContractLessees { get; set; } = new List<Contract>();

    public virtual ICollection<Contract> ContractLessors { get; set; } = new List<Contract>();

    public virtual ICollection<CurrentResident> CurrentResidents { get; set; } = new List<CurrentResident>();

    public virtual ICollection<MaintenanceRequest> MaintenanceRequestAgents { get; set; } = new List<MaintenanceRequest>();

    public virtual ICollection<MaintenanceRequest> MaintenanceRequestLessees { get; set; } = new List<MaintenanceRequest>();

    public virtual ICollection<Order> OrderLessees { get; set; } = new List<Order>();

    public virtual ICollection<Order> OrderLessors { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Role Role { get; set; }

    public virtual Wallet Wallet { get; set; }
}