// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Apt
{
    public string AptId { get; set; }

    public string PosterId { get; set; }

    public string OwnerName { get; set; }

    public string OwnerPhone { get; set; }

    public string OwnerEmail { get; set; }

    public string Name { get; set; }

    public double? Area { get; set; }

    public string Address { get; set; }

    public string AddressLink { get; set; }

    public int ProvinceId { get; set; }

    public int DistrictId { get; set; }

    public int WardId { get; set; }

    public int AptCategoryId { get; set; }

    public int AptStatusId { get; set; }

    public int NumberOfRoom { get; set; }

    public int NumberOfSlot { get; set; }

    public string Note { get; set; }

    public double? Rating { get; set; }

    public int ApproveStatusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool? Status { get; set; }

    public virtual AptCategory AptCategory { get; set; }

    public virtual AptStatus AptStatus { get; set; }

    public virtual ICollection<AptImage> AptImages { get; set; } = new List<AptImage>();

    public virtual ICollection<AptUtility> AptUtilities { get; set; } = new List<AptUtility>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<AccountLikedApt> AccountLikedApt { get; set; } = new List<AccountLikedApt>();
}