// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class AptImage
{
    public string AptId { get; set; }

    public string ImageUrl1 { get; set; }

    public string ImageUrl2 { get; set; }

    public string ImageUrl3 { get; set; }

    public string ImageUrl4 { get; set; }

    public string ImageUrl5 { get; set; }

    public string ImageUrl6 { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Apt Apt { get; set; }
}