// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class AptUtility
{
    public int Id { get; set; }

    public string AptId { get; set; }

    public int UtilityId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Apt Apt { get; set; }

    public virtual Utility Utility { get; set; }
}