// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Order
{
    public string OrderId { get; set; }

    public int TransactionTypeId { get; set; }

    public string PostId { get; set; }

    public string SenderId { get; set; }

    public decimal Amount { get; set; }

    public decimal IncurredCost { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime? CancelledAt { get; set; }

    public int PaymentStatusId { get; set; }

    public virtual Post Post { get; set; }

    public virtual Account Sender { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}