// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class PostRequire
{
    public int Id { get; set; }

    public string AccountId { get; set; }

    public string PostId { get; set; }

    public string Note { get; set; }

    public int ApproveStatusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Post Post { get; set; }
}