// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentEase.Data.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public int TransactionTypeId { get; set; }

    public string OrderId { get; set; }

    public int PaymentAttempt { get; set; }

    public string PaymentCode { get; set; }

    public decimal TotalAmount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime? CancelledAt { get; set; }

    public int PaymentStatusId { get; set; }

    public virtual Order Order { get; set; }

    public virtual TransactionType TransactionType { get; set; }
}