# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
      target: final
    environment:
      - DB_CONNECTION_STRING=Server=103.112.211.244,1433;Database=RentEase;User ID=SA;Password=Itjustapassword1@;TrustServerCertificate=True;Encrypt=false;
    ports:
      - "6969:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rentease.rule=Host(`103.112.211.244`)"  # HTTP rule
      - "traefik.http.routers.rentease.entrypoints=http"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.rentease.middlewares=redirect-to-https"
      - "traefik.http.routers.rentease-secure.rule=Host(`103.112.211.244`)"  # HTTPS rule
      - "traefik.http.routers.rentease-secure.entrypoints=https"
      - "traefik.http.routers.rentease-secure.tls=true"
    networks:
      - traefik

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.tls.certificates.certFile=/root/traefik/traefik.crt"
      - "--entrypoints.websecure.tls.certificates.keyFile=/root/traefik/traefik.key
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/traefik/traefik.crt:/root/traefik/traefik.crt"
      - "/root/traefik/traefik.key:/root/traefik/traefik.key"
      - "/root/traefik/dynamic.yaml:/etc/traefik/dynamic.yaml"  # Gắn cấu hình động
    networks:
      - traefik

networks:
  traefik:
    external: true

      
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

